services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghost-monitor-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true  # Для отслеживания изменений файлов
    volumes:
      - .:/app  # Монтируем текущую директорию
      - /app/node_modules  # Исключаем node_modules
      - /app/.next  # Исключаем .next
    working_dir: /app
    command: npm run dev